name = "CoOptimalTransport"
uuid = "8fbf8d06-8d49-4e5f-b299-41f622036d5f"
authors = ["Paul <paul.berg@univ-ubs.fr>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Flux"]
