name = "CoOptimalTransport"
uuid = "8fbf8d06-8d49-4e5f-b299-41f622036d5f"
authors = ["Paul <paul.berg@univ-ubs.fr>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]